feat: Added sharing functionality
HF6-PROJECT/web pull request #30
Opened 2023-10-11 15:58 UTC by frederikpyt

## Description
- Fixed the CORS issue when using ngrok locally
- Added share action on both file & folder contextmenu
- Added "Shared with me" tab
- Made the active tab visually appear as active

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2023-10-11 16:10 UTC, kristianbinau requested changes
Haven't looked at design or tested yet. This is just looking at the code

2023-10-11 16:10 UTC, kristianbinau commented on src/components/item/SharingBrowser.vue
Shouldn't we remove the fetching from `Browser.vue` and just give the items to it through a prop.
Then we could have a `SharingBrowser.vue` & a `FileBrowser.vue` or something like that.

2023-10-11 16:10 UTC, kristianbinau commented on src/components/item/ShareItemModal.vue
> +	return ((initialsRegex.shift()?.[1] || '') + (initialsRegex.pop()?.[1] || '')).toUpperCase();
Make helper functions or something

2023-10-11 16:10 UTC, kristianbinau commented on src/components/item/ShareItemModal.vue
> +>([]);
Ugly TS

2023-10-11 16:27 UTC, frederikpyt commented on src/components/item/SharingBrowser.vue
But the behavior is different. You shouldn't be able to open the "global" context menu in the SharingBrowser

2023-10-12 19:14 UTC, kristianbinau approved these changes
Awesome job, Comrade Pytlick🫡

2023-10-12 19:14 UTC, merged