feat: Added Shortcut functionality
HF6-PROJECT/web pull request #32
Opened 2023-10-16 08:07 UTC by Anders164a

## Description

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2023-10-17 10:55 UTC, kristianbinau requested changes

2023-10-17 10:55 UTC, kristianbinau commented on src/components/item/docs/Docs.vue
> +					>
Do something like this instead
```suggestion
					<a
						:href="(modelValue instanceof ShortcutClass) ? url(`u/docs/${modelValue.linkedItemId}`)  : url(`u/docs/${modelValue.id}`)"
						target="_blank"
						class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
						>{{ t('fileBrowser.docs.action.openInNewTab') }}</a
					>
```

2023-10-17 10:55 UTC, kristianbinau commented on src/components/item/docs/Docs.vue
> +					>
In all ContextMenues where it's only 1 value that changes

2023-10-17 10:55 UTC, kristianbinau commented on src/components/item/docs/Docs.vue
> +						>{{ t('fileBrowser.shortcut.rename') }}</a
Change all shortcut translations to match those of Folders, Files & Docs
```suggestion
						>{{ t('fileBrowser.shortcut.action.edit') }}</a
```

2023-10-17 10:55 UTC, kristianbinau commented on src/components/item/CreateShortcutModal.vue
> +				<h1 class="ml-2 mr-auto">Mine Filer</h1>
Translations????

2023-10-17 10:55 UTC, kristianbinau commented on src/lib/items/factory.ts
> +		}
```suggestion
		if (ShortcutClass.isShortcut(object)) {
			const shortcutClass = new ShortcutClass(object);
			await shortcutClass.setLinkedItem(object.linkedItemId);
			return shortcutClass;
		}
```

2023-10-17 10:55 UTC, kristianbinau commented on src/lib/items/shortcuts.ts
> +	linkedItem: FileClass | ShortcutClass | undefined;
```suggestion
	linkedItem: FileClass | ShortcutClass | DocsType | undefined;
```

2023-10-17 10:55 UTC, kristianbinau commented on src/lib/items/shortcuts.ts
> +		}
Use `Folder.isFolder()` and the others

2023-10-17 10:55 UTC, kristianbinau commented on src/lib/items/shortcuts.ts
> +
Maybe also check if object has `linkedItemId` and that it is a number

2023-10-17 10:55 UTC, kristianbinau commented on src/lib/items/shortcuts.ts
> +	public blobUrl: string | undefined;
Wat

2023-10-18 11:00 UTC, frederikpyt submitted a review, later dismissed

2023-10-18 11:11 UTC, frederikpyt approved these changes

2023-10-18 11:12 UTC, kristianbinau approved these changes

2023-10-18 11:12 UTC, merged